// The bundled dataset. It is generated by this repository rather than
// downloaded, so a clean checkout can run the demo and the benchmark with no
// network access at all.
#pragma once

#include <cstddef>
#include <string>

namespace trident {

struct DatasetSpec {
    std::size_t papers = 2000;
    std::size_t authors = 400;
    std::size_t venues = 16;
    std::size_t organisations = 30;
    std::size_t topics = 12;
    // Fixed by default, because a benchmark over a dataset that changes between
    // runs measures nothing.
    unsigned seed = 20260819u;
    // Emits the small RDFS schema (subclass, subproperty, domain, range) along
    // with the data, so the inference pass has something to work on.
    bool with_schema = true;
};

// Returns a Turtle document. The generator is deterministic: the same spec gives
// the same bytes on any platform, because it uses only integer arithmetic over a
// fixed pseudo random sequence.
std::string generate_dataset(const DatasetSpec& spec);

// Number of triples the document contains, without parsing it. Useful for the
// benchmark, which wants to divide by it.
std::size_t count_lines_of_data(const std::string& turtle);

}  // namespace trident
