#include "trident/generator.hpp"

#include <cstdint>
#include <sstream>
#include <vector>

namespace trident {

namespace {

// A 64 bit linear congruential generator. std::mt19937 would do as well, but the
// distributions in the standard library are free to differ between
// implementations, and a dataset that differs between platforms cannot be used
// to compare measurements.
class Random {
public:
    explicit Random(std::uint64_t seed) : state_(seed ? seed : 0x9E3779B97F4A7C15ull) {}
    std::uint64_t next() {
        state_ = state_ * 6364136223846793005ull + 1442695040888963407ull;
        return state_ >> 17;
    }
    std::size_t below(std::size_t bound) {
        return bound == 0 ? 0 : static_cast<std::size_t>(next() % bound);
    }

private:
    std::uint64_t state_;
};

const char* const kGivenNames[] = {"Ana", "Boris", "Cvetan", "Dara", "Emil", "Fani",
                                   "Georgi", "Hristo", "Iva", "Jana", "Kalin", "Lora",
                                   "Milen", "Nadia", "Ognian", "Petya"};
const char* const kFamilyNames[] = {"Angelov", "Borisova", "Chakarov", "Dimitrov",
                                    "Enev", "Filipova", "Gerov", "Hadzhiev",
                                    "Ivanova", "Kolev", "Lazarov", "Mihaylova"};
const char* const kTopicWords[] = {"indexing", "reasoning", "provenance", "federation",
                                   "alignment", "compression", "streaming", "validation",
                                   "embedding", "caching", "partitioning", "sampling"};
const char* const kTitleHead[] = {"On", "Towards", "Revisiting", "Scalable", "Adaptive",
                                  "Practical", "Efficient", "Incremental"};
const char* const kTitleTail[] = {"in triple stores", "for linked data", "under updates",
                                  "at web scale", "with bounded memory",
                                  "in embedded systems"};
const char* const kCountries[] = {"BG", "DE", "FR", "NL", "PL", "GR"};

template <std::size_t N>
const char* pick(const char* const (&table)[N], Random& random) {
    return table[random.below(N)];
}

}  // namespace

std::string generate_dataset(const DatasetSpec& spec) {
    Random random(spec.seed);
    std::ostringstream out;

    out << "# Generated by trident_gen, part of the Trident repository.\n"
        << "# Deterministic for a given specification: seed " << spec.seed << ", "
        << spec.papers << " papers, " << spec.authors << " authors.\n"
        << "@prefix ex:   <http://example.org/> .\n"
        << "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n"
        << "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .\n\n";

    if (spec.with_schema) {
        out << "# --- schema ---------------------------------------------------\n"
            << "ex:Paper rdfs:subClassOf ex:Publication .\n"
            << "ex:Publication rdfs:subClassOf ex:Work .\n"
            << "ex:Author rdfs:subClassOf ex:Person .\n"
            << "ex:Organisation rdfs:subClassOf ex:Agent .\n"
            << "ex:Person rdfs:subClassOf ex:Agent .\n"
            << "ex:mainAuthor rdfs:subPropertyOf ex:author .\n"
            << "ex:author rdfs:domain ex:Publication .\n"
            << "ex:author rdfs:range ex:Person .\n"
            << "ex:affiliation rdfs:range ex:Organisation .\n\n";
    }

    out << "# --- venues ---------------------------------------------------\n";
    for (std::size_t v = 0; v < spec.venues; ++v) {
        out << "ex:venue" << v << " a ex:Venue ; ex:name \"Workshop on "
            << pick(kTopicWords, random) << " " << (v + 1) << "\" .\n";
    }

    out << "\n# --- topics ---------------------------------------------------\n";
    for (std::size_t t = 0; t < spec.topics; ++t) {
        out << "ex:topic" << t << " a ex:Topic ; rdfs:label \"" << kTopicWords[t % 12]
            << "\"@en .\n";
    }

    out << "\n# --- organisations --------------------------------------------\n";
    for (std::size_t o = 0; o < spec.organisations; ++o) {
        out << "ex:org" << o << " a ex:Organisation ; ex:name \"Institute " << (o + 1)
            << "\" ; ex:country \"" << pick(kCountries, random) << "\" .\n";
    }

    out << "\n# --- authors --------------------------------------------------\n";
    for (std::size_t a = 0; a < spec.authors; ++a) {
        out << "ex:author" << a << " a ex:Author ;\n"
            << "    ex:name \"" << pick(kGivenNames, random) << " " << pick(kFamilyNames, random)
            << "\" ;\n"
            << "    ex:affiliation ex:org" << random.below(spec.organisations) << " ;\n"
            << "    ex:hIndex " << (1 + random.below(40)) << " ";
        // Only some authors have a homepage, which is what makes OPTIONAL worth
        // demonstrating on this dataset.
        if (random.below(100) < 35) {
            out << ";\n    ex:homepage <http://example.org/people/person" << a << "> ";
        }
        out << ".\n";
    }

    out << "\n# --- papers ---------------------------------------------------\n";
    for (std::size_t p = 0; p < spec.papers; ++p) {
        std::size_t author_count = 1 + random.below(3);
        out << "ex:paper" << p << " a ex:Paper ;\n"
            << "    ex:title \"" << pick(kTitleHead, random) << " " << pick(kTopicWords, random)
            << " " << pick(kTitleTail, random) << "\" ;\n"
            << "    ex:year " << (2010 + random.below(16)) << " ;\n"
            << "    ex:venue ex:venue" << random.below(spec.venues) << " ;\n"
            << "    ex:topic ex:topic" << random.below(spec.topics) << " ;\n"
            << "    ex:citationCount " << random.below(120) << " ;\n"
            << "    ex:mainAuthor ex:author" << random.below(spec.authors) << " ";
        for (std::size_t k = 1; k < author_count; ++k) {
            out << ";\n    ex:author ex:author" << random.below(spec.authors) << " ";
        }
        std::size_t cites = random.below(4);
        for (std::size_t k = 0; k < cites && p > 0; ++k) {
            out << ";\n    ex:cites ex:paper" << random.below(p) << " ";
        }
        out << ".\n";
    }

    return out.str();
}

std::size_t count_lines_of_data(const std::string& turtle) {
    std::size_t count = 0;
    for (char c : turtle) {
        if (c == '\n') ++count;
    }
    return count;
}

}  // namespace trident
